### ISSUE TITLE
ERROR: Named volume "home/kevin/appdata/kitana:/app/data:rw" is used in service "kitana" but no declaration was found in the volumes section.

### ISSUE THREAD

**Issue by kevindd992002** [pannal/Kitana#38]
Here's the contents of my docker-compose.yml file but it is not working when I do a `docker-compose up -d`

```
  kitana:
    image: pannal/kitana:latest
    container_name: kitana
    volumes:
     - home/kevin/appdata/kitana:/app/data
    ports:
      - "31337:31337"
    dns:
      - 192.168.20.100
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Manila
```

ERROR: Named volume "home/kevin/appdata/kitana:/app/data:rw" is used in service "kitana" but no declaration was found in the volumes section.

I have several docker containers with the same structure in the same docker-compose.yml running without issues. What could cause this?
